### ISSUE TITLE
RuntimeError: CUDA error: misaligned address on 2080ti when using ViTL14

### ISSUE THREAD

**Issue by Ainaemaet** [lowfuel/progrockdiffusion#100]
I'm aware a 2080ti is not optimal for that model, but I'm not getting CUDA out of memory except on more demanding ViTL models. RN50x16 runs fine - but regardless of other models used, I get misaligned address when using ViTL14.
Outside of different model combinations and re-installing Pytorch, I haven't tried anything.

```Image 1 of 1: :   0%|                                                                                                   | 0/300 [00:00<?, ?it/s]

All image(s) finished.
Traceback (most recent call last):
  File "prd.py", line 2809, in <module>
    do_run(batch_image)
  File "prd.py", line 1583, in do_run
    for j, sample in enumerate(samples):
  File "q:\progrockdiffusion\progrockdiffusion\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 900, in ddim_sample_loop_progressive
    eta=eta,
  File "q:\progrockdiffusion\progrockdiffusion\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 674, in ddim_sample
    out = self.condition_score(cond_fn, out_orig, x, t, model_kwargs=model_kwargs)
  File "q:\progrockdiffusion\progrockdiffusion\guided-diffusion\guided_diffusion\respace.py", line 102, in condition_score
    return super().condition_score(self._wrap_model(cond_fn), *args, **kwargs)
  File "q:\progrockdiffusion\progrockdiffusion\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 400, in condition_score
    x, self._scale_timesteps(t), **model_kwargs
  File "q:\progrockdiffusion\progrockdiffusion\guided-diffusion\guided_diffusion\respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "prd.py", line 1483, in cond_fn
    prompt_grad = torch.autograd.grad(clip_losses.sum() * args.clip_guidance_scale[1000 - t_int], x_in)[0] / args.cutn_batches[1000 - t_int]
  File "Q:\Users\my_user_name\anaconda3\envs\progrockdiffusion\lib\site-packages\torch\autograd\__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prd.py", line 2944, in <module>
    torch.cuda.empty_cache()
  File "Q:\Users\my_user_name\anaconda3\envs\progrockdiffusion\lib\site-packages\torch\cuda\memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.```

**Comment by lowfuel** [comment]
Also, please run nvidia-smi and tell me what CUDA version it shows.

**Comment by Ainaemaet** [comment]
Hi, thank you for getting back to me. 

Pytorch version: 1.10.2
CUDA Version: 11.7

Most of the reports I've seen say they fixed the error by downgrading Pytorch to 1.10.2, but that's what I'm running.

**Comment by Ainaemaet** [comment]
Ok, I had no idea. I only followed the directions as provided here and never even thought to check! I really appreciate the help. 

I installed torch with 
pip install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

**Comment by lowfuel** [comment]
Hah, no worries, I didn't know either. Let me see if I can get you a different install command to try.

**Comment by Ainaemaet** [comment]
Sounds good. :D

**Comment by lowfuel** [comment]
Okay well I installed the lastest torch for cuda 11.6 and my machine went haywire. So... don't do that. :P 

Maybe try this:
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 --force-reinstall
```
Get us to the latest version that supports cu113 and we can try to go from there.

**Comment by Ainaemaet** [comment]
Ok, well that seems to have done the trick! 
Not only is it running ViTL14, but it's taking less time than when I was running the other models (I had assumed it would take more time, even if I were running 2 'lesser' models previously in its place). 
Also, the resulting images I'm getting in comparison to what I had with other combinations is great!! I can still see where the other models would be handy, but wow this is exciting!  

I'm getting a couple deprecation warnings regarding some parameters (as below) but that's ok as it doesn't look like anything that will effect me at this moment anyhow. 

Thanks!!!! I'm looking forwards to that OpenCLIP implementation (🙏) now more than ever! 😁

```Q:\Users\my_user_name\anaconda3\envs\progrockdiffusion\lib\site-packages\torchvision\models\_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
Q:\Users\my_user_name\anaconda3\envs\progrockdiffusion\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: Q:\Users\my_user_name\anaconda3\envs\progrockdiffusion\lib\site-packages\lpips\weights\v0.1\vgg.pth

Loading CLIP Models:
-- ViT-L/14
-- RN50


Starting Run: Default(31) at frame 0
Using seed 290223749

Starting batch!
Skipping 0 steps

Prompt for step 0: ['several huge mirrors inside a solar system', 'Stalker vision,Hyperfocal,Studio Ghibli,Poster Art,8k,Blender Cycles, Deviantart popular deviations:30']
Image 1 of 8: :  54%|██████████████████████████████████▎```

**Comment by lowfuel** [comment]
Excellent!

**Comment by kjhenner** [comment]
This finally got it it running for me as well. Thanks!!
