### ISSUE TITLE
Memory use change

### ISSUE THREAD

**Issue by gmq** [lowfuel/progrockdiffusion#102]
Hi!

Since #89 (or probably #82) was merged progrockdiffusion fails with an out of memory error.
> RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.00 GiB total capacity; 7.51 GiB already allocated; 0 bytes free; 7.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

If I roll back to 72840b6bd0fcb907ae749a004728d4695d8def45 it works without any problem.

The only change to the default settings are the prompt and the models:
```
    "ViTB32": 1.0,
    "ViTB16": 1.0,
    "ViTL14": 1.0,
    "ViTL14_336": false,
    "RN101": false,
    "RN50": 1.0,
    "RN50x4": false,
    "RN50x16": false,
    "RN50x64": false,
```

**Comment by lowfuel** [comment]
Thanks for the issue report. I will look into it. Sounds like maybe something in the clip model manager might be using more memory.
In the short term you can try changing vitl14 to 0.5 and see if that gets it going.

**Comment by lowfuel** [comment]
Possible source of the issue found, hopefully will have a fix in tomorrow.

**Comment by kjhenner** [comment]
Yep, I had neglected to remove the previous CLIP model loading step after moving it to the ModelManager class. Oops! Resolved now. @gmq Let us know if that improves memory performance for you.

**Comment by gmq** [comment]
That solved it, thanks!
