### ISSUE TITLE
RuntimeError: CUDA error: misaligned address

### ISSUE THREAD

**Issue by boxcartony** [lowfuel/progrockdiffusion#34]
Hey. Been trying to get this up and running but when running the python prd.py command it starts but then dies partway through giving me some errors that look like this. No idea what to do about it. Any advice?

RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prd.py", line 3054, in <module>
    torch.cuda.empty_cache()
  File "C:\Users\njmar\.conda\envs\progrockdiffusion\lib\site-packages\torch\cuda\memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by lowfuel** [comment]
Hmm... that's coming from one of the libraries used, not PRD itself. Can you tell me more about the hardware you're using?
Also if you could run nvidia-smi from your command prompt and paste the results here that'd be great.

**Comment by boxcartony** [comment]
Just a pretty standard desktop PC. 

Thu May 12 21:14:43 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.59       Driver Version: 512.59       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:08:00.0  On |                  N/A |
|  0%   55C    P5    26W / 215W |    705MiB /  8192MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1744    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A      4940    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A      7544    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      9776    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     10700    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     10996    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     11700    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     13348    C+G   ...8wekyb3d8bbwe\GameBar.exe    N/A      |
|    0   N/A  N/A     14272    C+G   ...\app-1.0.9004\Discord.exe    N/A      |
|    0   N/A  N/A     14744    C+G   ...in7x64\steamwebhelper.exe    N/A      |
|    0   N/A  N/A     15132    C+G   ...les (x86)\Steam\steam.exe    N/A      |
|    0   N/A  N/A     15504    C+G   ...aming\Spotify\Spotify.exe    N/A      |
|    0   N/A  N/A     16736    C+G   ...y\ShellExperienceHost.exe    N/A      |
+-----------------------------------------------------------------------------+

**Comment by lowfuel** [comment]
(resolved on discord, card was running out of memory)

**Comment by zloc-alz** [comment]
I ran into a similar problem while using a RTX2080Ti. Solved by setting `"ViTL14": false` in `settings.json`

**Comment by lowfuel** [comment]
Unfortunately I think 8gb vram is not enough for Vitl14. Maybe I should turn it off in the provided settings. I'll probably do that.

**Comment by zloc-alz** [comment]
Well my card has 11gb of vram, and if im right ive seen people with RTX3060 8gb VRAM run it successfully in default settings, although with lower resolution.
