### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by randompaga** [lowfuel/progrockdiffusion#35]
Hi,
my hardware info:
GPU NVIDIA Tesla T4   1*16GB
CPU 20 cores
Memory  80GB

`{
  "batch_name": "Default",
  "text_prompts": {
    "0": [
      "A beautiful painting of a Castle in the Scottish Highlands, underexposed and overcast, by Asher Brown Durand, featured on ArtStation."
    ]
  },
  "n_batches": 1,
  "steps": 250,
  "display_rate": 10,
  "width": 1080,
  "height": 1920,
  "set_seed": "random_seed",
  "image_prompts": {},
  "clip_guidance_scale": "auto",
  "tv_scale": 0,
  "range_scale": 150,
  "sat_scale": 0,
  "cutn_batches": 1,
  "max_frames": 10000,
  "interp_spline": "Linear",
  "init_image": null,
  "init_scale": 1000,
  "skip_steps": 0,
  "frames_scale": 1500,
  "frames_skip_steps": "60%",
  "perlin_init": false,
  "perlin_mode": "mixed",
  "skip_augs": false,
  "randomize_class": true,
  "clip_denoised": false,
  "clamp_grad": true,
  "clamp_max": "auto",
  "fuzzy_prompt": false,
  "rand_mag": 0.05,
  "eta": "auto",
  "diffusion_model": "512x512_diffusion_uncond_finetune_008100",
  "use_secondary_model": true,
  "sampling_mode": "ddim",
  "diffusion_steps": 1000,
  "ViTB32": true,
  "ViTB16": true,
  "ViTL14": false,
  "ViTL14_336": false,
  "RN101": false,
  "RN50": true,
  "RN50x4": false,
  "RN50x16": false,
  "RN50x64": false,
  "cut_overview": "[5]*400+[1]*600",
  "cut_innercut": "[1]*400+[5]*600",
  "cut_ic_pow": 1,
  "cut_icgray_p": "[0.2]*400+[0]*600",
  "animation_mode": "None",
  "key_frames": true,
  "angle": "0:(0)",
  "zoom": "0: (1), 10: (1.05)",
  "translation_x": "0: (0)",
  "translation_y": "0: (0)",
  "video_init_path": "/content/training.mp4",
  "extract_nth_frame": 2,
  "intermediate_saves": 0,
  "stop_early": 0,
  "fix_brightness_contrast": true,
  "high_contrast_threshold": 80,
  "high_contrast_adjust_amount": 0.85,
  "high_contrast_start": 20,
  "high_contrast_adjust": true,
  "low_contrast_threshold": 20,
  "low_contrast_adjust_amount": 2,
  "low_contrast_start": 20,
  "low_contrast_adjust": true,
  "high_brightness_threshold": 180,
  "high_brightness_adjust_amount": 0.85,
  "high_brightness_start": 0,
  "high_brightness_adjust": true,
  "low_brightness_threshold": 40,
  "low_brightness_adjust_amount": 1.15,
  "low_brightness_start": 0,
  "low_brightness_adjust": true,
  "sharpen_preset": "Off",
  "gobig_orientation": "vertical",
  "keep_unsharp": false
}`

RuntimeError: CUDA out of memory. Tried to allocate 120.00 MiB (GPU 0; 15.75 GiB total capacity; 14.47 GiB already allocated; 101.62 MiB free; 14.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by lowfuel** [comment]
The only thing I'm seeing in your settings that might cause this is the resolution.
Try lowering it maybe to 1024x1792, if you still have problems go down to 960x1664, etc, until you find your sweet spot.

**Comment by randompaga** [comment]
Yeah, it works for me, thanks.

**Comment by randompaga** [comment]
How to achieve GPU concurrency, I execute two tasks at the same time, but still get RuntimeError: CUDA out of memory.

**Comment by lowfuel** [comment]
If you're using two gpus, try adding

--cuda 1

To the second prd command so that it uses the other gpu

**Comment by randompaga** [comment]
> Do you mean you have two GPUs?

No,I mean i have one GPU.
Now, each processing needs to occupy more than 10000 m of the video memory when total GPU video memory is only 16000m. 
If I make two requests to one GPU to let the program generate two pictures at the same time,GPU video memory will not be enough. It will get RuntimeError: CUDA out of memory.
Is there any way to make GPU concurrent or reduce the video memory occupation of code?  
Thanks for your reply!
